CREATE TABLE CAR(
   CAR_ID SERIAL PRIMARY KEY NOT NULL,
   MANUFACTURER_NAME TEXT NOT NULL,
   MODEL_NAME        TEXT NOT NULL,
   SERIAL_NUMBER     VARCHAR(17) NOT NULL,
   WEIGHT            INT  NOT NULL,
   METRICS_ABBRV      VARCHAR(10) NOT NULL,
   PRICE             NUMERIC NOT NULL,
   CREATED_DATE      TIMESTAMP NOT NULL
);

CREATE TABLE SALES_PERSON (
    SALES_PERSON_ID SERIAL PRIMARY KEY NOT NULL,
    SALES_PERSON_NAME TEXT NOT NULL,
    SALES_PERSON_PHONE INT NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID SERIAL PRIMARY KEY NOT NULL,
    CUSTOMER_NAME TEXT NOT NULL,
    CUSTOMER_PHONE INT NOT NULL,
    CREATED_DATE TIMESTAMP
);


CREATE TABLE SALE_TRANSACTION(
   TRANSACTION_ID SERIAL PRIMARY KEY NOT NULL,
   CUSTOMER_ID    INT     NOT NULL,
   SALES_PERSON_ID   INT NOT NULL,
   CAR_ID            INT NOT NULL,
   TRANSACTION_DATE  TIMESTAMP  NOT NULL,
   CONSTRAINT fk_sales_person_id FOREIGN KEY (SALES_PERSON_ID) REFERENCES SALES_PERSON (SALES_PERSON_ID),
   CONSTRAINT fk_car_id FOREIGN KEY (CAR_ID) REFERENCES CAR (CAR_ID),
   CONSTRAINT fk_customer_id FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
   UNIQUE (SALES_PERSON_ID, CAR_ID)
);