SELECT SALE_TRANSACTION.customer_id, SUM (SALE_TRANSACTION.price) AS total
FROM SALE_TRANSACTION
INNER JOIN CAR ON CAR.CAR_ID = SALE_TRANSACTION.CAR_ID
GROUP BY SALE_TRANSACTION.customer_id;

WITH result AS (
    SELECT CAR.MANUFACTURER_NAME, SUM (SALE_TRANSACTION.price) AS total
    FROM CAR
    INNER JOIN SALE_TRANSACTION ON SALE_TRANSACTION.CAR_ID = CAR.CAR_ID
    GROUP BY CAR.MANUFACTURER_NAME; 
)
SELECT MANUFACTURER_NAME
FROM result
order by total desc
limit 3;